CRM/urls.py
from django.contrib import admin
from django.urls import path, include
from project.urls import prj_cli_list_patterns
from client.urls import home_patterns
from .views import PersonalInfo, personal_info, signUpView, logInView, signoutView, successSignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(home_patterns)),
    path('client/', include('client.urls')),
    path('project/', include('project.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('', include(prj_cli_list_patterns)),
    path('', include('interactions.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('personal/', personal_info, name='personal_info'),
    # path('personal/', PersonalInfo.as_view(), name='personal'),
    path('accounts/signup/', signUpView, name='signup'),
    path('accounts/login/', logInView, name='login'),
    path('accounts/logout', signoutView, name='logout'),
    path('accounts/success_signup', successSignUpView, name='success_signup'),
]

interactions/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('client/<int:client_id>/interactions/', InteractionsForClient.as_view(), name='interactions_client'),
    path('project/<int:project_id>/interactions/', InteractionsForProject.as_view(), name='interactions_project'),    
    path('interactions/', InteractionsList.as_view(), name='interactions_list'),
    path('interactions/detail/<int:interaction_id>/', InteractionDetail.as_view(), name='interaction_detail'),
    path('interaction/create/', InteractionCreate.as_view(), name = 'interaction_create'),
    path('interaction/update/<int:interaction_id>/', InteractionUpdate.as_view(), name = 'interaction_update'),
    path('interaction/delete/<int:interaction_id>/', InteractionDelete.as_view(), name = 'interaction_delete'),
]

interactions/models.py
from django.db import models
from django.urls.base import reverse
from tinymce import models as tinymce_models
from django.contrib.auth.models import User

class Interaction(models.Model):
  project = models.ForeignKey('project.Project', on_delete=models.CASCADE, related_name='interaction_project', verbose_name='Проект')
  client = models.ForeignKey('client.Client', on_delete=models.CASCADE, related_name='interaction_client', verbose_name='Клиент')

  CHOICE = 'CH'
  REQUEST = 'RQ'
  LETTER = 'LT'
  SITE = 'ST'
  INITIATIVE = 'INT'

  MESSAGE_CHANNEL_CHOICE = [
    (CHOICE, 'Взаимодействие не выбрано'),
    (REQUEST, 'Заявка'),
    (LETTER, 'Письмо'),
    (SITE, 'Сайт'),
    (INITIATIVE, 'Инициатива компании'),
  ]
  message_channel = models.CharField(max_length=3, choices=MESSAGE_CHANNEL_CHOICE, default=CHOICE, verbose_name='Канал обращения')
  manager = models.ManyToManyField(User, related_name='interaction_manager', verbose_name='Менеджер')
  description = tinymce_models.HTMLField('Описание')

  NOTHING = 'NTH'
  MINUS_ONE = 'M1'
  MINUS_TWO = 'M2'
  MINUS_THREE = 'M3'
  MINUS_FOUR = 'M4'
  MINUS_FIVE = 'M5'
  PLUS_ONE = 'P1'
  PLUS_TWO = 'P2'
  PLUS_THREE = 'P3'
  PLUS_FOUR = 'P4'
  PLUS_FIVE = 'P5'

  GRADE_CHOICE = [
    (MINUS_FIVE, '-5'),
    (MINUS_FOUR, '-4'),
    (MINUS_THREE, '-3'),
    (MINUS_TWO, '-2'),
    (MINUS_ONE, '-1'),
    (NOTHING, 'Нет оценки'),
    (PLUS_ONE, '+1'),
    (PLUS_TWO, '+2'),
    (PLUS_THREE, '+3'),
    (PLUS_FOUR, '+4'),
    (PLUS_FIVE, '+5'),
  ]
  grade = models.CharField(max_length=3, choices=GRADE_CHOICE, default=NOTHING, verbose_name='Оценка')

  def __str__(self):
    return 'Взаимодействие'

  class Meta:
    verbose_name = 'Взаимодействие'
    verbose_name_plural = 'Взаимодействия'

  def get_absolute_url(self):
    return reverse('interaction_detail', kwargs={'interaction_id': self.pk})  

interactions/views.py
from django.urls.base import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from client.models import Client
from project.models import Project
from .models import Interaction
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


class InteractionsForClient(LoginRequiredMixin,  PermissionRequiredMixin, DetailView):
  '''Отображение взаимодействий для одного клиента'''
  model = Client
  paginate_by = 4
  template_name = 'interactions/interactions_client.html'
  pk_url_kwarg = 'client_id'
  extra_context = {'title': 'Взаимодействия по клиенту'}
  allow_empty = True
  permission_required = 'interactions.view_interaction'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['interactions_client_list'] = Interaction.objects.filter(client_id=self.kwargs['client_id']).order_by(self.request.GET.get('orderby', 'project'))
    return context


class InteractionsForProject(LoginRequiredMixin,  PermissionRequiredMixin, DetailView):
  '''Отображение взаимодействий для одного проекта'''
  model = Project
  paginate_by = 4
  template_name = 'interactions/interactions_project.html'
  pk_url_kwarg = 'project_id'
  extra_context = {'title': 'Взаимодействия по проекту'}
  allow_empty = True
  permission_required = 'interactions.view_interaction'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['interactions_project_list'] = Interaction.objects.filter(project_id=self.kwargs['project_id']).order_by(self.request.GET.get('orderby', 'project'))
    return context


class InteractionsList(LoginRequiredMixin,  PermissionRequiredMixin, ListView):
  '''Отображение взаимодействий для всех клиентов'''
  model = Interaction
  paginate_by = 4
  template_name = 'interactions/interactions_list.html'
  extra_context = {'title': 'Взаимодействия'}
  permission_required = 'interactions.view_interaction'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['interactions_list'] = Interaction.objects.all().order_by(self.request.GET.get('orderby', 'project'))
    return context


class InteractionDetail(LoginRequiredMixin,  PermissionRequiredMixin, DetailView):
  '''Отображение детальное отображение информации взаимодействия'''
  model = Interaction
  fields = '__all__'
  template_name = 'interactions/interaction_detail.html'
  pk_url_kwarg = 'interaction_id'
  context_object_name = 'interaction_detail'
  # success_url = reverse_lazy('interactions_list')
  extra_context = {'title': 'Информация о взаимодействии'}
  permission_required = 'interactions.view_interaction'

class InteractionCreate(LoginRequiredMixin,  PermissionRequiredMixin, CreateView):
  '''Создание нового взаимодействия'''
  model = Interaction
  fields = '__all__'
  template_name = 'interactions/interaction_create.html'
  # pk_url_kwarg = 'interaction_id'
  success_url = reverse_lazy('interactions_list')
  extra_context = {'title': 'Создание взаимодействия'}
  permission_required = 'interactions.add_interaction'

class InteractionUpdate(LoginRequiredMixin,  PermissionRequiredMixin, UpdateView):
  '''Редактирование взаимодействия'''
  model = Interaction
  fields = '__all__'
  template_name = 'interactions/interaction_update.html'
  pk_url_kwarg = 'interaction_id'
  success_url = reverse_lazy('interactions_list')
  extra_context = {'title': 'Обновление взаимодействия'}
  permission_required = 'interactions.change_interaction'


class InteractionDelete(LoginRequiredMixin,  PermissionRequiredMixin, DeleteView):
  '''Удаление взаимодействия'''
  model = Interaction
  fields = '__all__'
  template_name = 'interactions/interaction_delete.html'
  pk_url_kwarg = 'interaction_id'
  success_url = reverse_lazy('interactions_list')
  extra_context = {'title': 'Удаление взаимодействия'}
  permission_required = 'interactions.delete_interaction'

interactions/templates/interactions/interaction_create.html
{% extends 'client/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{{ form.media }}
<form method="post" class="uniform">
  {% csrf_token %}
  {{ form | crispy }}
  <input type="submit" value="Создать"></input>
</form>
{% endblock %}

interactions/templates/interactions/interaction_delete.html
{% extends 'client/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{{ form.media }}
<form method="post" class="uniform">
  {% csrf_token %}
  <div class="container px-4">
    <div class="row border p-3 mt-5 text-danger fs-4">
      Вы действительно хотите удалить взаимодействие?
    </div>
    <div class="row p-3 mt-5">
      <input type="submit" value="Удалить"></input>
    </div>
  </div>
</form>
{% endblock %}

interactions/templates/interactions/interaction_detail.html
{% extends 'client/base.html' %}
{% block content %}
  <h6>Проект: &nbsp;<em>{{interaction_detail.project}}</em></h6>
  <h6>Клиент: <em>{{interaction_detail.client}}</em></h6>
  <h6>Канал обращения: &nbsp;<em>{{interaction_detail.get_message_channel_display}}</em></h6>
  <h6>Менеджер: &nbsp;<em>
    {% for n in interaction_detail.manager.all %}{{n}} &nbsp;{% endfor %}</em></h6>
  <div style="border-style: double; margin-right: 30px;">
    <h6>Описание: </h6> {% autoescape off %}{{interaction_detail.description}}{% endautoescape %}
  </div>
  <h6>Оценка: &nbsp;<em>{{interaction_detail.get_grade_display}}</em></h6>

  <div class="mt-4">
    <a href="{% url 'interaction_update' interaction_detail.pk %}" class="text-secondary fs-6">Редактировать взаимодействие</a>
  </div>
  <div class="mt-2">
    <a href="{% url 'interaction_delete' interaction_detail.pk %}" class="text-danger fs-6">Удалить взаимодействие</a>
  </div>
{% endblock %}

interactions/templates/interactions/interaction_update.html
{% extends 'client/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{{ form.media }}
<form method="post" class="uniform">
  {% csrf_token %}
  {{ form | crispy }}
  <input type="submit" value="Обновить"></input>
</form>
{% endblock %}

interactions/templates/interactions/interactions_client.html
{% extends 'client/base.html' %}

{% block content %}
<h1>{{title}}:</h1>
  <form action="{% url 'interactions_client' client.pk %}" method="get">
    <div class="row">
      <div class="m-2">
        <button type="submit" class="btn btn-outline-secondary btn-sm" name="orderby" value="project">˄ Проект</button>
        <button type="submit" class="btn btn-outline-secondary btn-sm" name="orderby" value="-project">˅ Проект</button>
        <button type="submit" class="btn btn-outline-secondary btn-sm" name="orderby" value="client">˄ Клиент</button>
        <button type="submit"class="btn btn-outline-secondary btn-sm" name="orderby" value="-client">˅ Клиент</button>
      </div>
    </div>
  </form>
<table class="table bg-light">
  <tr>
    <th>Проект</th>
    <th>Клиент</th>
    <th>Канал обращения</th>
    <th>Менеджер</th>
    <th>Описание</th>
    <th>Оценка</th>
  </tr>
    {% for field in interactions_client_list %}
    <tr>
      <td>
        <a href="{{ field.project.get_absolute_url }}">{{field.project}}</a> 
      </td>
      <td>
        <a href="{{ field.client.get_absolute_url }}">{{field.client}}</a> 
      </td>      
      <td>{{field.get_message_channel_display}}</td>
      <td>
        {% for n in field.manager.all %}
        <p>{{n}}</p>
        {% endfor %}
      </td>
      <td>
        {% autoescape off %}
        {{field.description}}
        {% endautoescape %}
      </td>
      <td>{{field.get_grade_display}}</td>
    </tr>  
    {% endfor %}
</table>
{% endblock %}

interactions/templates/interactions/interactions_list.html
{% extends 'client/base.html' %}

{% block content %}
<h1>{{title}}:</h1>
  <form action="{% url 'interactions_list' %}" method="get">
    <div class="row">
      <div class="m-2">
        <button type="submit" class="btn btn-outline-secondary btn-sm" name="orderby" value="project">˄ Проект</button>
        <button type="submit" class="btn btn-outline-secondary btn-sm" name="orderby" value="-project">˅ Проект</button>
        <button type="submit" class="btn btn-outline-secondary btn-sm" name="orderby" value="client">˄ Клиент</button>
        <button type="submit"class="btn btn-outline-secondary btn-sm" name="orderby" value="-client">˅ Клиент</button>
      </div>
    </div>
  </form>
<table class="table bg-light">
  <tr>
    <th>Взаимодействие</th>
    <th>Проект</th>
    <th>Клиент</th>
    <th>Канал обращения</th>
    <th>Менеджер</th>
    <th>Описание</th>
    <th>Оценка</th>
  </tr>
    {% for field in interactions_list %}
    <tr>
      <td>
        <a href="{{ field.get_absolute_url }}">Номер {{field.pk}}</a> 
      </td>
      <td>
        <a href="{{ field.project.get_absolute_url }}">{{field.project}}</a> 
      </td>
      <td>
        <a href="{{ field.client.get_absolute_url }}">{{field.client}}</a> 
      </td>      
      <td>{{field.get_message_channel_display}}</td>
      <td>
        {% for n in field.manager.all %}
        <p>{{n}}</p>
        {% endfor %}
      </td>
      <td>
        {% autoescape off %}
        {{field.description}}
        {% endautoescape %}
      </td>
      <td>{{field.get_grade_display}}</td>
    </tr>  
    {% endfor %}
</table>
{% endblock %}

interactions/templates/interactions/interactions_project.html
{% extends 'client/base.html' %}

{% block content %}
<h1>{{title}}:</h1>
  <form action="{% url 'interactions_project' project.pk %}" method="get">
    <div class="row">
      <div class="m-2">
        <button type="submit" class="btn btn-outline-secondary btn-sm" name="orderby" value="project">˄ Проект</button>
        <button type="submit" class="btn btn-outline-secondary btn-sm" name="orderby" value="-project">˅ Проект</button>
        <button type="submit" class="btn btn-outline-secondary btn-sm" name="orderby" value="client">˄ Клиент</button>
        <button type="submit"class="btn btn-outline-secondary btn-sm" name="orderby" value="-client">˅ Клиент</button>
      </div>
    </div>
  </form>
<table class="table bg-light">
  <tr>
    <th>Проект</th>
    <th>Клиент</th>
    <th>Канал обращения</th>
    <th>Менеджер</th>
    <th>Описание</th>
    <th>Оценка</th>
  </tr>
    {% for field in interactions_project_list %}
    <tr>
      <td>
        <a href="{{ field.project.get_absolute_url }}">{{field.project}}</a> 
      </td>
      <td>
        <a href="{{ field.client.get_absolute_url }}">{{field.client}}</a> 
      </td>      
      <td>{{field.get_message_channel_display}}</td>
      <td>
        {% for n in field.manager.all %}
        <p>{{n}}</p>
        {% endfor %}
      </td>
      <td>
        {% autoescape off %}
        {{field.description}}
        {% endautoescape %}
      </td>
      <td>{{field.get_grade_display}}</td>
    </tr>  
    {% endfor %}
</table>
{% endblock %}