CRM/urls.py
from django.contrib import admin
from django.urls import path, include
from project.urls import prj_cli_list_patterns
from client.urls import home_patterns
from .views import PersonalInfo, personal_info, signUpView, logInView, signoutView, successSignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(home_patterns)),
    path('client/', include('client.urls')),
    path('project/', include('project.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('', include(prj_cli_list_patterns)),
    path('', include('interactions.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('personal/', personal_info, name='personal_info'),
    # path('personal/', PersonalInfo.as_view(), name='personal'),
    path('accounts/signup/', signUpView, name='signup'),
    path('accounts/login/', logInView, name='login'),
    path('accounts/logout', signoutView, name='logout'),
    path('accounts/success_signup', successSignUpView, name='success_signup'),
]

client/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('detail/<int:client_id>/', ClientDetail.as_view(), name='client_detail'),
    path('create/', ClientCreate.as_view(), name = 'client_create'),
    path('update/<int:client_id>/', ClientUpdate.as_view(), name = 'client_update'),
    path('delete/<int:client_id>/', ClientDelete.as_view(), name = 'client_delete'),
]

home_patterns = [
    path('', ClientList.as_view(), name='client_list'),
]

client/models.py
from django.db import models
from django.db.models.fields import CharField, DateTimeField, EmailField
from django.urls import reverse
from tinymce import models as tinymce_models



class Email(models.Model):
  '''Модель email'''
  email = EmailField('Электронная почта', max_length=100)
  client = models.ForeignKey('Client', on_delete=models.SET_NULL, null=True, related_name='email_client')

  def __str__(self):
      return self.email

  class Meta:
    verbose_name = 'Электронная почта'
    verbose_name_plural = 'Электронная почта'


class Phone(models.Model):
  '''Модель телефон'''
  phone = CharField('Телефон', max_length=50)
  client = models.ForeignKey('Client', on_delete=models.SET_NULL, null=True, related_name='phone_client')

  def __str__(self):
      return self.phone

  class Meta:
    verbose_name = 'Телефон'
    verbose_name_plural = 'Телефоны'


class Client(models.Model):
  '''Модель клиент'''
  company_name = CharField(verbose_name='Название компании', max_length=100)
  full_name_director = CharField(verbose_name='Ф.И.О. директора', max_length=100)
  short_description = tinymce_models.HTMLField('Краткое описание')
  date_create = DateTimeField(verbose_name='Дата создания',auto_now_add=True)
  date_change = DateTimeField(verbose_name='Дата изменения', auto_now=True)
  address = CharField(verbose_name='Адрес', max_length=200)

  def __str__(self):
      return self.company_name

  def get_absolute_url(self):
    return reverse('client_detail', kwargs={'client_id': self.pk})  

  class Meta:
    verbose_name = 'Клиент'
    verbose_name_plural = 'Клиенты'
    ordering = ['company_name', 'date_create']

client/forms.py
from django import forms
from .models import *
from tinymce.widgets import TinyMCE
from django.forms.models import inlineformset_factory




PhoneFormset = inlineformset_factory(Client, Phone, fields=('phone',), can_delete=True, extra=1)

EmailFormset = inlineformset_factory(Client, Email, fields=('email',), can_delete=True, extra=1)


CreatePhoneFormset = inlineformset_factory(Client, Phone, fields=('phone',), can_delete=True, extra=4)

CreateEmailFormset = inlineformset_factory(Client, Email, fields=('email',), can_delete=True, extra=4)

client/views.py
from django.urls.base import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import PhoneFormset, EmailFormset, CreateEmailFormset, CreatePhoneFormset
from .models import *
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


class ClientList(LoginRequiredMixin, ListView):
# class ClientList(ListView):
  '''Отображение списка клиентов'''
  # login_url = '/login/'
  # redirect_field_name = 'redirect_to'
  model = Client
  paginate_by = 4
  template_name = 'client/client_list.html'
  context_object_name = 'client_list'
  extra_context = {'title': 'Список клиентов'}

  def get_ordering(self):
      return self.request.GET.get('orderby')


class ClientDetail(LoginRequiredMixin, DetailView):
  '''Детальная информация о клиенте'''
  model = Client
  template_name = 'client/client_detail.html'
  pk_url_kwarg = 'client_id'
  context_object_name = 'client_detail'
  extra_context = {'title': 'Информация о клиенте'}


class ClientCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
  '''Форма создания клиента'''
  model = Client
  fields = '__all__'
  template_name = 'client/client_create.html'
  success_url = reverse_lazy('client_list')
  permission_required = 'client.add_client'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['title'] = 'Создание клиента'
    if self.request.POST:
        context['phone_formset'] = CreatePhoneFormset(self.request.POST, instance=self.object)
        context['phone_formset'].full_clean()
        
        context['email_formset'] = CreateEmailFormset(self.request.POST, instance=self.object)
        context['email_formset'].full_clean()
    else:
        context['phone_formset'] = CreatePhoneFormset(instance=self.object)
        context['email_formset'] = CreateEmailFormset(instance=self.object)
    return context

  def form_valid(self, form):
    context = self.get_context_data(form=form)
    phone_formset = context['phone_formset']
    email_formset = context['email_formset']
    if phone_formset.is_valid() and email_formset.is_valid():
      response = super().form_valid(form)
      phone_formset.instance = self.object
      phone_formset.save()
      email_formset.instance = self.object
      email_formset.save()
      return response
    else:
      return super().form_invalid(form)




class ClientUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
  '''Форма редактирования клиента'''  
  model = Client
  fields = '__all__'
  template_name = 'client/client_update.html'
  pk_url_kwarg = 'client_id'
  success_url = reverse_lazy('client_list')
  permission_required = 'client.change_client'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['title'] = 'Редактирование клиента'
    if self.request.POST:
        context['phone_formset'] = PhoneFormset(self.request.POST, instance=self.object)
        context['phone_formset'].full_clean()
        
        context['email_formset'] = EmailFormset(self.request.POST, instance=self.object)
        context['email_formset'].full_clean()
    else:
        context['phone_formset'] = PhoneFormset(instance=self.object)
        context['email_formset'] = EmailFormset(instance=self.object)
    return context

  def form_valid(self, form):
    context = self.get_context_data(form=form)
    phone_formset = context['phone_formset']
    email_formset = context['email_formset']
    if phone_formset.is_valid() and email_formset.is_valid():
      response = super().form_valid(form)
      phone_formset.instance = self.object
      phone_formset.save()
      email_formset.instance = self.object
      email_formset.save()
      return response
    else:
      return super().form_invalid(form)


class ClientDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
  '''Форма удаления клиента'''
  model = Client
  fields = ['company_name', 'full_name_director', 'short_description', 'address']
  pk_url_kwarg = 'client_id'
  template_name = 'client/client_delete.html'
  success_url = reverse_lazy('client_list')
  extra_context = {'title': 'Удаление клиента'}
  permission_required = 'client.delete_client'

client/templates/client/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <title>{{title}}</title>
</head>
  <body>
    <div>
      <div>
        <ul class="nav nav-tabs">
          {% url 'client_list' as client_list_page %}
          <li class="nav-item">
            <a class="nav-link
            {% if client_list_page == request.path %}
            active 
            {% endif %}
            " href="{% url 'client_list' %}">Все клиенты</a>
          </li>
          {% url 'project_list' as project_list_page %}
          <li class="nav-item">
            <a class="nav-link
            {% if project_list_page == request.path %}
            active 
            {% endif %}
            " href="{% url 'project_list' %}">Все проекты</a>
          </li>
          {% url 'interactions_list' as interactions_list_page %}
          <li class="nav-item">
            <a class="nav-link
            {% if interactions_list_page == request.path %}
            active 
            {% endif %}
            " href="{% url 'interactions_list' %}">Взаимодействия</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link
              {% url 'personal' as personal%}
              {% if personal == request.path %}
                active 
              {% endif %}
              " style="text-decoration:underline;" href="{% url 'personal_info' %}" tabindex="-1" aria-disabled="true">Личный кабинет: {{ user.get_username }}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link
              {% url 'logout' as logout%}
              {% if login == request.path %}
            active 
              {% endif %}
              " href="{% url 'logout' %}">Выход</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link
              {% url 'login' as login%}
              {% if login == request.path %}
              active 
              {% endif %}
              " href="{% url 'login' %}">Вход</a>
            </li>
          {% endif %}    
        </ul>
      </div>
      <div class="mt-3 ms-5 me-5">
        {% block content %}
        {% endblock %}
      </div>
      <div class="ms-5 ps-5">
        <nav aria-label="Page navigation example">
          <ul class="pagination pagination-sm">
            {% if page_obj.has_previous %}
              <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Пред.</a></li>
            {% endif %}
            {% for p in paginator.page_range %}
            {% if page_obj.number == p %}
              <li class="page-item active"><a class="page-link" href="?page={{p}}">{{p}}</a></li>
            {% else %}
              <li class="page-item"><a class="page-link" href="?page={{p}}">{{p}}</a></li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">След.</a></li>
            {% endif %}
          </ul>
        </nav>
      </div>
    </div>
</body>
</html>

client/templates/client/client.html
{% extends 'client/base.html' %}
{% block content %}
  <h3>Название компании: &nbsp;<em>{{client_detail.company_name}}</em></h3>
  <h4>Ф.И.О.: <em>{{client_detail.full_name_director}}</em></h4>
  <div style="border-style: double; margin-right: 30px;">
    <h4>Краткое описание: </h4> {% autoescape off %}{{client_detail.short_description}}{% endautoescape %}
  </div>
  <h4>Дата создания: &nbsp;<em>{{client_detail.date_create}}</em></h4>
  <h4>Дата изменения: &nbsp;<em>{{client_detail.date_change}}</em></h4>
  <h4>Адрес: &nbsp;<em>{{client_detail.address}}</em></h4>
  {% for phone in client_detail.phone_set.all %}
    <h4>Телефон: &nbsp;<em>{{phone}}</em></h4>
  {% endfor %}
  {% for email in client_detail.email_set.all %}
    <h4>Электронная почта: &nbsp;<em>{{email}}</em></h4>
  {% endfor %}
  <br>
  <a href="{% url 'client_update' client_detail.pk %}">Редактировать данные клиента</a>
{% endblock %}

client/templates/client/client_create.html
{% extends 'client/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{{ form.media }}
<form method="post" class="uniform">
  {% csrf_token %}
  {{ form | crispy }}
  {{ phone_formset | crispy }}
  {{ email_formset | crispy }}
  <input type="submit" value="Создать"></input>
</form>
{% endblock %}

client/templates/client/client_delete.html
{% extends 'client/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{{ form.media }}
<form method="post" class="uniform">
  {% csrf_token %}
  <div class="container px-4">
    <div class="row border p-3 mt-5 text-danger fs-4">
      Вы действительно хотите удалить клиента?
    </div>
    <div class="row p-3 mt-5">
      <input type="submit" value="Delete"></input>
    </div>
  </div>
</form>
{% endblock %}

client/templates/client/client_detail.html
{% extends 'client/base.html' %}
{% block content %}
  <h4>Название компании: &nbsp;<em>{{client_detail.company_name}}</em></h4>
  <h6>Ф.И.О.: <em>{{client_detail.full_name_director}}</em></h6>
  <div style="border-style: double; margin-right: 30px;">
    <h6>Краткое описание: </h6> {% autoescape off %}{{client_detail.short_description}}{% endautoescape %}
  </div>
  <h6>Дата создания: &nbsp;<em>{{client_detail.date_create}}</em></h6>
  <h6>Дата изменения: &nbsp;<em>{{client_detail.date_change}}</em></h6>
  <h6>Адрес: &nbsp;<em>{{client_detail.address}}</em></h6>
  {% for phone in client_detail.client_phones.all %}
    <h6>Телефон: &nbsp;<em>{{phone}}</em></h6>
  {% endfor %}
  {% for email in client_detail.client_emails.all %}
    <h6>Электронная почта: &nbsp;<em>{{email}}</em></h6>
  {% endfor %}
  <div class="mt-4">
    <a href="{% url 'project_client_list' client_detail.pk %}" class="text-info fs-6">Проекты клиента</a>
  </div>
  <div class="mt-2">
    <a href="{% url 'interactions_client' client_detail.pk %}" class="text-info fs-6">Взаимодействия по клиенту</a>
  </div>
  <div class="mt-4">
    <a href="{% url 'client_update' client_detail.pk %}" class="text-secondary fs-6">Редактировать данные клиента</a>
  </div>
  <div class="mt-2">
    <a href="{% url 'client_delete' client_detail.pk %}" class="text-danger fs-6">Удалить данные клиента</a>
  </div>
{% endblock %}

client/templates/client/client_list.html
{% extends 'client/base.html' %}

{% block content %}
<h1>{{title}}:</h1>
  <form action="{% url 'client_list' %}" method="get">
    <div class="row">
      <div class="m-2">
        <button type="submit" class="btn btn-outline-secondary btn-sm" name="orderby" value="company_name">˄ имя</button>
        <button type="submit" class="btn btn-outline-secondary btn-sm" name="orderby" value="-company_name">˅ имя</button>
        <button type="submit" class="btn btn-outline-secondary btn-sm" name="orderby" value="date_create">˄ дата создания</button>
        <button type="submit"class="btn btn-outline-secondary btn-sm" name="orderby" value="-date_create">˅ дата создания</button>
      </div>
    </div>
  </form>
<ul>
  {% for field in client_list %}
    <li>
      <h5>Имя клиента: <a href="{{ field.get_absolute_url }}">{{field.company_name}}</a></h5> 
      Дата создания: {{field.date_create}}
      &nbsp; &nbsp;
      <!-- {% for phone in field.client_phones.all %}
        {{phone}}
      {% endfor %} -->
      <hr>
    </li>
  {% endfor %}
</ul>
{% endblock %}

client/templates/client/client_update.html
{% extends 'client/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{{ form.media }}
<form method="post" class="uniform">
  {% csrf_token %}
  {{ form | crispy }}
  {{ phone_formset | crispy }}
  {{ email_formset | crispy }}
  <input type="submit" value="Обновить"></input>
</form>
{% endblock %}